### ISSUE TITLE
Creating multiple instances of the same api client

### ISSUE THREAD

**Issue by azakordonets** [Manweill/swagger-axios-codegen#104]
Hi, i might be mistaken, since i don't work with Javascript/Typescript that often, but from what i understand the only way to set customly modified axios library to service is this way : 
```javascript
import axios from 'axios'
import { ProductService } from './generated/Product'

const getAxiosInstance = serviceKey => {
  return axios.create({
    baseURL: process.env[`API_END_POINT_${serviceKey}`],
    timeout: 1000,
    headers: { 'X-Custom-Header': 'foobar' },
  });
};

ProductService.axios = getAxiosInstance('PRODUCT');

export { ProductService };
```
I suppose that in this case i can't have 2 ProductService clients that have different API_KEYS ? Because we don't set axios on class instance, but instead we would just override the field in the file. Or am i wrong ? 

How complicated/easy would it be to make axios part of service class ? Right now it's just exported function: 
```javascript
export function axios(configs: IRequestConfig, resolve: (p: any) => void, reject: (p: any) => void): Promise<any> {
```

**Comment by Manweill** [comment]
Yes, it can have two instance. but it is a anyother mode, and then I don't have time to realize it. Welcome PR。

**Comment by azakordonets** [comment]
Clear, thanks. I will give it a try
