### ISSUE TITLE
Support for 'required' Swagger keyword

### ISSUE THREAD

**Issue by jkulcsar** [Manweill/swagger-axios-codegen#106]
Hello,
First of all thank you for this great library, been using it for a while in several projects.
I came across today a situation where in the` swagger.json` file the `required `keyword is used on one property but not the others, those being obviously optional. The generated data model should mark these optional with ? however it doesn't.
For example:
```
      "MyRequestType": {
        "required": [
          "ArticleNumber"
        ],
        "type": "object",
        "properties": {
          "ArticleNumber": {
            "type": "string"
          },
          "ArticleDescription": {
            "type": "string"
          }
        }
      }
```
generates:
```
export class MyRequestType {
  /**  */
  'ArticleNumber': string;

  /**  */
  'ArticleDescription': string;

  constructor(data: undefined | any = {}) {
    this['ArticleNumber'] = data['ArticleNumber'];
    this['ArticleDescription'] = data['ArticleDescription'];
  }

  public static validationModel = {
    ArticleNumber: { required: true }
  };
}

```
From what I'm reading and seen with another generator, the property ` 'ArticleDescription': string;` should be ` 'ArticleDescription'?: string;`
Is this perhaps configurable? I haven't seen any other configuration parameters that would help with this, currently I'm using
```
...
  generateValidationModel: true,
  strictNullChecks: true,
...
```
Thank you for your help or any suggestions.

**Comment by Manweill** [comment]
@jkulcsar 
this config is use on class model

**Comment by fairking** [comment]
Maybe apart from `strictNullChecks: true` the code must check if the type is nullable or not:
https://github.com/Manweill/swagger-axios-codegen/blob/master/src/templates/template.ts

![image](https://user-images.githubusercontent.com/13495631/88426229-be7a1500-cde8-11ea-894f-2e0e5d52b192.png)

could be something like:
```
return `
  /** ${description || ''} */
  ${decorators}
  '${filedName}'${canNull || type.isNullable ? '?' : ''}:${type};
  `
```

However based on the answer from stackoverflow the `?` character makes field optional, not nullable. So not nullable fields will require value assigned. It is configurable in typescript by the option `strictNullChecks`.
https://stackoverflow.com/a/17220359/1143349
