### ISSUE TITLE
ability to strip prefix or suffix from operationId's (which must be globally unique) for method name

### ISSUE THREAD

**Issue by wizofaus** [Manweill/swagger-axios-codegen#107]
Currently codegen takes our swagger and uses the "tags" metadata to generate a typescript class for each resource, for which there are then your typical create/get/list/delete type methods.  But in order to achieve this we have to violate the swagger 2 spec which requires globally-unique operationIds.
What I'd like is the ability to have codegen strip the suffix off each operationId that matches the resource name (as per the "tags" metadata), so that our operationIds can be, e.g. getFoo, getBar, getWidget but the functions generated are FooService.get(), BarService.get(), WidgetService.get() etc., as per what we have now.
Is this a reasonable request? I assume there's no "plugin" mechanism for generating function names?
(NB using the 'path', the other alternative for methodNameMode, is not feasible).

**Comment by Manweill** [comment]
@wizofaus 
See in `ISwaggerOptions`.

**Comment by wizofaus** [comment]
methodNameMode is either operationId or path, how will that help?  Bit confused why you closed this...

**Comment by Manweill** [comment]
@wizofaus 
I think your mean  that you need to generate unique method name?

**Comment by wizofaus** [comment]
I mean that I need *globally* unique operationIds to comply with the swagger spec, e.g.
getFoo, getBar, getWidget, updateFoo, updateBar, udpateWidget etc.
But the resource name (Foo/Bar/Widget) doesn't need to be included in the method name because it's already in the name of the typescript class:
FooService.get
BarService.get
WidgetService.get

i.e. I'd like an option that when generating the methodName, it takes the operationId and strips off the "resource name"/service name from the end.

**Comment by Manweill** [comment]
I got it.
I think you can put all the methods in a default Service, like that 
```js
class Service{
  static [operationId](){}
}
```

**Comment by wizofaus** [comment]
We want to keep the generated client code as it is now - apart from the fact we have a substantial amount of code calling, it looks clean and is well-organized and easy to read.
But the only way to achieve it is to violate the swagger 2.0/openapi spec and NOT have globally unique operationIds.

**Comment by Manweill** [comment]
Emmm....., I am a little confused now.
What do you want ,now.
Codegen currently has two methods for generating method names.
```js

// use operationId
[tagName]Service {
   static [operationId](){}
}

// use path
[tagName]Service {
   static [last-path](){}
}
```
Usually we recommend using operationId, because it is the specification of swagger2.0, and it can be customized according to requirements.
And then, the `tagName` is just for grouping

**Comment by wizofaus** [comment]
I'm saying I'd like 
```
[tagName]Service {
   static [operationId-with-tagName-suffix-removed](){}
}

```

**Comment by Manweill** [comment]
> I'm saying I'd like
> 
> ```
> [tagName]Service {
>    static [operationId-with-tagName-suffix-removed](){}
> }
> ```

it is a bit unreasonable

**Comment by wizofaus** [comment]
As long as the only operations we have for specifying the methodName are via operationId or path, then there's no way of getting the client stubs we want and complying with the swagger 2.0 specification requiring globally unique operationId's.

I'm happy to put up a PR for it if you accept external contributions.

**Comment by Manweill** [comment]
Okey, Welcome!
But, it only remove methodName's suffix

**Comment by wizofaus** [comment]
I'll add a new methodNameMode which is operationIdWithoutTagName then?

**Comment by wizofaus** [comment]
Actually I went with shortOperationId, and it's basically just `req.operationId.replace(req.className, '')`, though that also required adding `className` to the IRequestMethods interface.
Unfortunately you're not using npm so I haven't quite figured out to compile locally, but hopefully it will work...

**Comment by Manweill** [comment]
> req.operationId.replace(req.className, '')
It is so bad. It should only remove at suffix. you can use `trimString()`  in `utils.ts`

**Comment by wizofaus** [comment]
Fair enough, tweaked a few things and put up a PR. I noticed none of your examples had `methodNameMode: 'operationId'` to test against, not sure if you have a process for creating new examples.

**Comment by Manweill** [comment]
new example by you.

**Comment by wizofaus** [comment]
I'm not sure what you're saying, you want me to add one before approving the PR?

**Comment by Manweill** [comment]
Yes. 
And then, `codegen` has a method similar to 'trimSuffix'.

**Comment by wizofaus** [comment]
I looked at the functions in utils.ts but they were too complex and not particularly efficient for what I needed.

**Comment by Manweill** [comment]
try it

**Comment by wizofaus** [comment]
Yep, I did, that's why I went with a simpler method that was more suitable to what I needed.

**Comment by wizofaus** [comment]
Thanks for merging, having trouble getting it to download the latest version, do you need to republish or something?
