### ISSUE TITLE
How to generate an interface with properties that are nullable

### ISSUE THREAD

**Issue by pbn4** [Manweill/swagger-axios-codegen#124]
I would like to have an interface with properties that are a union of a specific type and a null instead of '?' (undefined), e.g.:

```
export interface A {
prop: string | null 
}
```

instead of:

```
export interface A {
prop?: string
}
```

is there a way to achieve that with this library?

**Comment by Manweill** [comment]
same with these example

**Comment by pbn4** [comment]
@Manweill They are not the same when strict null check is enabled. So is there a way to generate this 1st kind of interface I specified?

**Comment by pbn4** [comment]
I see that here https://github.com/Manweill/swagger-axios-codegen/blob/master/src/templates/template.ts#L44  is a check for nullable prop but an optional operator is always used. What do you think about adding optional operator based on `required` and `| null` union based on "nullable"?

**Comment by Manweill** [comment]
set `codgen`  `options.strictNullCheck=true`

**Comment by Manweill** [comment]
```typescript
let obj: {
  a: number | null | undefined;
  b?: number | null | undefined;
} = {

}

```
![image](https://user-images.githubusercontent.com/7599653/99343546-145b5700-28c9-11eb-9072-750a8f724840.png)

@pbn4 There is only one difference between the two writing methods. When initializing obj, `a` must be defined, `b` is not

**Comment by Manweill** [comment]
Long time is not active!
