### ISSUE TITLE
Cannot read property 'imports' of undefined

### ISSUE THREAD

**Issue by lamuertepeluda** [Manweill/swagger-axios-codegen#13]
Hi,

I think you should add a check at this line of code https://github.com/Manweill/swagger-axios-codegen/blob/master/src/requestCodegen/index.ts#L54 and line above, like

```
if(refResponseType && parsedParameters && Array.isArray(parsedParameters.imports)){
  parsedParameters.imports.push(responseType)
}
```

I get this error
```
error TypeError: Cannot read property 'imports' of undefined
    at Object.requestCodegen (/Users/vito/Development/JavaScript/VISCA/swagger-codegen/node_modules/swagger-axios-codegen/dist/requestCodegen/index.js:40:34)
    at codegen (/Users/vito/Development/JavaScript/VISCA/swagger-codegen/node_modules/swagger-axios-codegen/dist/index.js:140:45)
    at generateApi (/Users/vito/Development/JavaScript/VISCA/swagger-codegen/apigen.js:24:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

which is also swallowed, i.e. `codegen()` does not throw, but also does not generate the api.

**Comment by Manweill** [comment]
@lamuertepeluda 
Hi, can you send your swagger.json to me

**Comment by lamuertepeluda** [comment]
hi @Manweill , it's at this [URL](https://backend.visca.cloud/dev/swagger-spec.json). I tried with both remoteURL and file options, same result.

**Comment by Manweill** [comment]
@lamuertepeluda 
Hei, you can try `swagger-axios-codegen@v0.5.1` again.

**Comment by Manweill** [comment]
@lamuertepeluda 
Hi, I fix `imports` bug in `v0.5.1`.
BTW, when I try with your `swagger-spec.json`  file, I find another problem. 
One tag like `Irrigation Block` , it has whitespace.
One type like this :
```js
"geometry": {
          "type": "geoJSON geometry"
},
```

**Comment by lamuertepeluda** [comment]
Hi @Manweill, 

thanks for investigating.  
I downloaded the latest version an it still occurs that it's swallowing exception, making it harder to debug, i.e. [this line](https://github.com/Manweill/swagger-axios-codegen/blob/ce1650b0fd9f953820479a329408d2e5e447eb0e/src/index.ts#L171) should definitely `throw` the error, in a way that a user program can detect its failure state. 

Maybe even better storing in a local variable and throwing it after unlinking files and the console.timeEnd() of line 177, like

```ts
let err = null
/*... do things */
catch(error){
   err = error
}
/*... do other things */
if(err){
   throw err;
}
```

Regarding the type name, they are autogenerated using [nest-swagger](https://github.com/nestjs/swagger) using TS definitions and reflect-metadata (our server is written entirely in TypeScript with nestjs).

Although we know that this nest-swagger module has for sure its good share of issues, we currently auto-generate client-side api module with this other generator named [swagger-es6](https://github.com/leopq/swagger-es6), and it's not having troubles with entity names.

I liked more your approach since your library is entirely in TS, and it also easily allows for using a separate axios instance, so I'm trying it. But I got stuck 😅 

Debugging with VSCode I found 2 different errors when running the codegen script, depending on methodNameMode

`operationId` leads to an error on [this line](https://github.com/Manweill/swagger-axios-codegen/blob/master/src/template.ts#L78)

`path` leads to an error [here](https://github.com/Manweill/swagger-axios-codegen/blob/master/src/index.ts#L196), that is the formatter fails because the class name is "Irrigation Block" instead of "IrrigationBlock"

Could calling `camelcase` at [this line](https://github.com/Manweill/swagger-axios-codegen/blob/4f23a67a0928844c778921683b415f3839faddf8/src/requestCodegen/index.ts#L30) help dealing with spaces tags and therefore in generated class names?

**Comment by Manweill** [comment]
Thanks for suggestion.
Let's look at each problem.
First, we can also replace spaces when the classname had whitespace.
Then, I search `geoJSON geometry` type. It dose not a base type in JS/TS. It need a method to tell the `codegen`, how it transform this type.
If these two problems are solved, continue to execute

**Comment by lamuertepeluda** [comment]
While the spaces problems looks simpler to be solved, how about setting a default type for all non-base JS/TS types?
I know it is less accurate, but `Object` or `any` should work.
Sadly  I don't think it's feasible to include type definitions through swagger.

Another solution may be using some generic, like `GeneratedClass<T>`, but it is not really easy to think about it in a way that actually works...

**Comment by Manweill** [comment]
emm...
In `Utils.toBaseType`, return default type `any` .
You can do this for the time being.

BTW, how about I provide an entry for a custom transform method

**Comment by lamuertepeluda** [comment]
this could definitely work, if you know the generated types in advance. But I would fallback with Object or any when not transformer is provided.

**Comment by Manweill** [comment]
Test in your project and commit PRs

**Comment by Manweill** [comment]
Hi @lamuertepeluda 

I double check your swagger.json. Your api was RESTful api. But it doesn't had `operationId` in the `swagger.json`

**Comment by lamuertepeluda** [comment]
Hi @Manweill you are indeed right, we are not (yet) using operationId in that API.
I must definitely rely on the `path` method

**Comment by Manweill** [comment]
The issue was too long
