### ISSUE TITLE
support for cancel token 

### ISSUE THREAD

**Issue by amirjr1378** [Manweill/swagger-axios-codegen#133]
change 
export interface IRequestOptions {
  headers?: any;
  baseURL?: string;
  responseType?: string;
}
to support cancel token 
it should be like

export interface IRequestOptions {
  headers?: any;
  baseURL?: string;
  responseType?: string;
  cancelToken: new CancelToken(function (cancel) {
  });
}

**Comment by Manweill** [comment]
good idea!
