### ISSUE TITLE
Does not work on amazon seller partner api openapi specs

### ISSUE THREAD

**Issue by digitalpacman** [Manweill/swagger-axios-codegen#138]
https://raw.githubusercontent.com/amzn/selling-partner-api-models/main/models/fulfillment-outbound-api-model/fulfillmentOutbound_2020-07-01.json

It doesn't create a ton of the models. Any of the array types it looks like.

NotificationEmailList

NotificationEmailList: {
type: "array",
description: "A list of email addresses that the seller provides that are used by Amazon to send ship-complete notifications to recipients on behalf of the seller.",
items: {
type: "string",
maxLength: 64
}
}

UpdateFulfillmentOrderItemList
ErrorList
Features

**Comment by Manweill** [comment]
@digitalpacman 
Hey~ 
In the `spec.json` , do not define like this with  the `NotificationEmailList`  and others array types.

example for `NotificationEmailList`:

```js
// in definitions
"NotificationEmailList": {
      "type": "string",
      "description": "A list of email addresses that the seller provides that are used by Amazon to send ship-complete notifications to recipients on behalf of the seller.",
      "maxLength": 64
    },
```

````js
// in request
 "notificationEmails": {
          "items": {
            "$ref": "#/definitions/NotificationEmailList",
            "type": "array"
          }
        },
````

```js
// after generate in request
/**  */
  notificationEmails?: NotificationEmailList[];


```

**Comment by Manweill** [comment]
inactive close
