### ISSUE TITLE
IRequestOptions doesn't allow to use every AxiosRequestConfig options in TypeScript strict mode.

### ISSUE THREAD

**Issue by AdrianoRuberto** [Manweill/swagger-axios-codegen#139]
I'm trying to use `onUploadProgress` when I'm uploading a file, but as I'm using TypeScript in strict mode, I can't pass it to the options.

The service call I'm trying to do:
```ts
FileService.upload({file}, {onUploadProgress: event => ...})
```

The problem is that the options don't extends `AxiosRequestConfig` but readd some of them ?

When I cast (ie: `{onUploadProgress: event => ...} as any`) the `onUploadProgress` is working fine.

I'm suggesting to use `AxiosRequestConfig` from the axios lib instead of creating an interface`IRequestOptions` as I don't see any custom option.

If you think there will be custom options that the lib will maybe use, just extends `IRequestOptions` with `AxiosRequestConfig` (and leave only customs option).

**Comment by Manweill** [comment]
emmm，I don‘t got

**Comment by AdrianoRuberto** [comment]
The generated service: 
```ts
export interface IRequestOptions {
  headers?: any;
  baseURL?: string;
  responseType?: string;
  transformRequest?: AxiosTransformer | AxiosTransformer[];
  transformResponse?: AxiosTransformer | AxiosTransformer[];
  cancelToken?: CancelToken;
}

export class FileService {
    static upload(params: {file: any} = {}, options: IRequestOptions = {}) { ... }
}
```

The problem with this is I can't call `FileService.upload({file}, {onUploadProgress: (event) => ....})` because `onUploadProgress` isn't declared in `IRequestOptions`.

There is 2 solutions I propose:
- Replace `IRequestOptions` by `AxiosRequestConfig` (because that's what the options for axios are)
- Extends `IRequestOptions` with `AxiosRequestConfig` to allow the usage of all the options of axios. This solution is maybe prefered if there are custom options.
