### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by lamuertepeluda** [Manweill/swagger-axios-codegen#14]
Hi @Manweill ,

it's me again. Since I found it hard debugging for #13 , I have a couple of improvements that I'd suggest you to add when you have time.

### Add Source Maps

I suggest you to add a tsconfig.json file with `compilerOptions.sourceMap: true`, or alternatively add `--sourceMap=true` to the [build](https://github.com/Manweill/swagger-axios-codegen/blob/master/package.json#L20) npm script.  
Other useful options for optimizing the build and source files are [here](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

### Template with a template library

I saw many templates defined as JS/TS template strings in template.ts. However they are hardly readable.
Maybe using a template library such as hanldebarsjs and having separated files for each template can improve readability and debugging of this important part of the code.

**Comment by Manweill** [comment]
Hi @lamuertepeluda 
In previous versions, the `swagger-axios-codegen` had sourceMap in lib.
However, I also use [`yarn link`](https://yarnpkg.com/en/docs/cli/link) to debugging.
And then,I delete the  `sourceMap` in package.
I will add `sourceMap` in next version.

About template library, welcome PR.
