### ISSUE TITLE
Handle missing names of parameters

### ISSUE THREAD

**Issue by vvsevolodovich** [Manweill/swagger-axios-codegen#141]
Imagine part of the spec: 

```
paths:
  /my/path:
    get:
      operationId: getData
      summary: getting data
      parameters:
        - $ref: '#/components/headers/Authorization'
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/start_date'
        - $ref: '#/components/parameters/end_date'
```

Formally, the param names are missing. The generator issuing an error:

getRequestParameters.js:19
        if (!v.name.includes('[0]')) {
                    ^

TypeError: Cannot read property 'includes' of undefined

There are 2 possible improvements here:

1) Improve the error message to something like "Missing required 'name' of parameter for <operationId>"
2) Handle that case extracting the parameter name from the name of the reference

**Comment by Manweill** [comment]
not supported like that. you can refer to example

**Comment by vvsevolodovich** [comment]
Yeah, I got it's not supported. The question is do we want to support? If not, would we like to improve the error mesage?
