### ISSUE TITLE
我想axios resolve(res)，该怎么配置

### ISSUE THREAD

**Issue by hemocy** [Manweill/swagger-axios-codegen#144]
由于项目之前都是resove(res),现在换用这个导出的api,返回的和以前不同，代码要改的地方太多。有没有方法或者配置项修改？
![image](https://user-images.githubusercontent.com/29173748/130024450-c9cf269d-86ad-4ecc-897c-2e10d69542f9.png)

**Comment by Manweill** [comment]
你这个应该是跟144同一个需求，不过我暂时没时间调整。先归到一类去。或者你们可以自己PR

**Comment by Manweill** [comment]
如果你不考虑返回结果的提示话，可以直接在 `axiosClient.interceptors.response.use`里面做处理

**Comment by hemocy** [comment]
还有个问题，生成的api返回值都是promise<any>,$ref没有生效一样 swaggerv3版本
![image](https://user-images.githubusercontent.com/29173748/130039153-3ee18527-e46d-4abd-8c73-3c814514d9e3.png)
这个$ref,生成代码后
![image](https://user-images.githubusercontent.com/29173748/130039444-b057bda3-18cd-40bc-9dcb-579836e1093e.png)
，如何生成正确的res.data类型，而不是都是any?
盼回复~thx

**Comment by Manweill** [comment]
![image](https://user-images.githubusercontent.com/7599653/130042384-689545cf-42f0-46dd-9621-3de3c3b971c9.png)

应该是这个的原因，这里需要是 `application/json`

**Comment by hemocy** [comment]
感谢大佬，have a nice day!
