### ISSUE TITLE
Cannot use isAxiosApiError

### ISSUE THREAD

**Issue by SinBirb** [Manweill/swagger-axios-codegen#151]
Hi,

because axios() gets defined as a custom function, I can't use `axios.isAxiosApiError()` ([docs](https://github.com/axios/axios#typescript)).

Is there another good way to use it?

**Comment by Manweill** [comment]
i not seet `axios.isAxiosApiError()`

**Comment by Manweill** [comment]
u can use an `interceptors.response`

**Comment by SpineEyE** [comment]
Sorry, I meant `axios.isAxiosError`. I don't want to use an interceptor because it's an error specific to one request.

**Comment by SinBirb** [comment]
Sorry, I meant axios.isAxiosError. I don't want to use an interceptor because it's an error specific to one request.

**Comment by Manweill** [comment]
i meant `axios` is default instance from lib
