### ISSUE TITLE
why is responseType omitted?

### ISSUE THREAD

**Issue by VincentVanclef** [Manweill/swagger-axios-codegen#152]
Hi there, why is responseType omitted? 

Ive got an endpoint which returns a FileResult, and thus i need to change the responseType from json to blob. Why is this omitted?

export interface FullRequestParams extends Omit<AxiosRequestConfig, "data" | "params" | "url" | "**responseType**"> {

Also, why isnt it possible to change this on the fly? Currently this:

```
const responseFormat = (format && this.format) || void 0;
```

Prevents me from changing it to any other type as this always returns undefined, unless i specify the format type in the constructor, which overwrites whatever setting i add later.

Regards, Vincent

**Comment by Manweill** [comment]
i dont get what you say
