### ISSUE TITLE
Version 0.15.1 Populated Services and ViewModels have Underscore in front of names

### ISSUE THREAD

**Issue by lucasdale99** [Manweill/swagger-axios-codegen#169]
The fix for 0.15.0 

https://github.com/Manweill/swagger-axios-codegen/commit/6c51ee6ae8ef2997dc5696dc14b0aaeaf05b7a53

Fixed the issue with names not showing up correctly, but now all the services and view models have an underscore in front of the name.

Link to previous issue: https://github.com/Manweill/swagger-axios-codegen/issues/168

**Comment by Manweill** [comment]
can u post your code?
