### ISSUE TITLE
urlFilters not work?

### ISSUE THREAD

**Issue by hemocy** [Manweill/swagger-axios-codegen#172]
i use both include&urlFilters to filter some url，the final genered file is empty, only use include is work well, only use urlfilters also get empty file

**Comment by hemocy** [comment]
could you please add feature for urlfilters can fitler a word in path ,not just prefix,,,well, now prefix dose'nt work though...

**Comment by hemocy** [comment]
i've fixed this 
![image](https://user-images.githubusercontent.com/29173748/224932041-0104dc86-2f06-41e2-95fb-f397e74dcb46.png)

**Comment by Manweill** [comment]
wellcome pr's

**Comment by hemocy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
