### ISSUE TITLE
Serious issue that requires immediate fixing. 从 swagger-axios-codegen@0.16.0 开始，npm 包发布异常，未正确生成dist

### ISSUE THREAD

**Issue by WangMingHua111** [Manweill/swagger-axios-codegen#184]
Starting from swagger-axios-codegen@0.16.0, there have been issues with the npm package release, as it failed to generate the 'dist' directory correctly.
![image](https://github.com/Manweill/swagger-axios-codegen/assets/51693922/3db55b3f-3563-437b-8c56-9674a95b559b)

**Comment by Manweill** [comment]
我检查一下，0.16 之后改为使用actions 自动发布

**Comment by Manweill** [comment]
重新发布了个新版，应该无问题了
