### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'format')

### ISSUE THREAD

**Issue by JaLe29** [Manweill/swagger-axios-codegen#189]
I am getting an error `TypeError: Cannot read properties of undefined (reading 'format')`  

Code:
```
const { codegen } = require('swagger-axios-codegen')

codegen({
    methodNameMode: 'operationId',
    source: require('./swagger.json'),
    outputDir: '.',
    useStaticMethod: true
});
```

JSON:
https://raw.githubusercontent.com/Manweill/swagger-axios-codegen/e155741a7ffcad654296ae68496a8682ed5b3f28/example/swagger3.json

Version:
` "swagger-axios-codegen": "^0.16.7",`

**Comment by Manweill** [comment]
fix in 0.16.8
