### ISSUE TITLE
can't support Generics

### ISSUE THREAD

**Issue by litianyiliwei** [Manweill/swagger-axios-codegen#22]
like

		"ClientResult«AuthUserDTO»": {
			"type": "object",
			"properties": {
				"data": {
					"$ref": "#/definitions/AuthUserDTO"
				},
				"msg": {
					"type": "string"
				},
				"success": {
					"type": "boolean"
				}
			},
			"title": "ClientResult«AuthUserDTO»"
		}

**Comment by Manweill** [comment]
`Generic` class is define  like `PagedResultDto[AlertMessageOutput]`
