### ISSUE TITLE
Generated file (service/index.ts) should be TypeScript strict mode complaint

### ISSUE THREAD

**Issue by SpearThruster** [Manweill/swagger-axios-codegen#23]

**Comment by Manweill** [comment]
What problems are you currently experiencing?

**Comment by SpearThruster** [comment]
Basically the fields generated on the class are being set via a `data` object (which is any) and there is a `key/string` iteration to set the field values. TypeScript complains that there is no gurantee that all fields will be set.

The workaround is to set `strict: false` in `tsconfig.json` which opens another can of worms.

**Comment by Manweill** [comment]
@SpearThruster 
Okey,  I see.
And then,  I will optimize it on the next version. can you set `strict: false` some days?
Or, you can push `PR` with it.

**Comment by Manweill** [comment]
Fixed in ` Ver 0.5.04`
