### ISSUE TITLE
Prefer 'as any' instead of '<any>' when doing type assertions  @typescript-eslint/no-angle-bracket-type-assertion

### ISSUE THREAD

**Issue by SpearThruster** [Manweill/swagger-axios-codegen#24]

**Comment by Manweill** [comment]
Adjust your rules or exclude the file

**Comment by SpearThruster** [comment]
Hi @Manweill ,

Sadly those rules are not configurable (from create-react-app) and this suggestion is also supported by TS core team. I can submit a PR.

**Comment by Manweill** [comment]
👌
