### ISSUE TITLE
Extend request options (baseURL, method, contentType)

### ISSUE THREAD

**Issue by LucaDe** [Manweill/swagger-axios-codegen#35]
Currently you can't configure baseURL, HTTP method (hardcoded to POST atm) and contentType (hardcoded as well).

I will do a PR for this :)

**Comment by Manweill** [comment]
@LucaDe 
So sorry~
I am a Bad coder

**Comment by Manweill** [comment]
`baseURL` usually like this `axios.default.baseURL = 'xxx.xxx.com'`
But your thoughts are not bad.
