### ISSUE TITLE
Array in swagger, but not array in codegen

### ISSUE THREAD

**Issue by nibytes** [Manweill/swagger-axios-codegen#37]
![изображение](https://user-images.githubusercontent.com/15169344/64479795-c88d2800-d1c4-11e9-839d-ac7fccce6270.png)
Swagger
![изображение](https://user-images.githubusercontent.com/15169344/64479809-0427f200-d1c5-11e9-9561-0d4a87404f98.png)
Generated code

**Comment by nibytes** [comment]
@Manweill Can you approve my PR?

**Comment by nibytes** [comment]
@Manweill When I can npm update package with fix?

**Comment by Manweill** [comment]
@nibytes Tomorrow

**Comment by nibytes** [comment]
> 
> 
> @nibytes Tomorrow

Ok thank you

**Comment by LucaDe** [comment]
I'm struggling with the same issue currently. Even though the param gets annotated correctly now, the data property is not set correctly. 
Currently it looks like this:
`{"0":{"from":"123","op":"add","path":"/path","value":{"name":"123"}}}`
But it should look like this:
`[{"from":"123","op":"add","path":"/path","value":{"name":"123"}}]`
