### ISSUE TITLE
Validation attributes

### ISSUE THREAD

**Issue by fairking** [Manweill/swagger-axios-codegen#50]
Would like to see something to be able to generate validation attributes among with model classes.
It would be really cool.

My view model looks like this:
![image](https://user-images.githubusercontent.com/13495631/66215866-56710b80-e6bc-11e9-882b-5d4182c06e3b.png)

I got my api like this:
![image](https://user-images.githubusercontent.com/13495631/66222281-b40b5500-e6c8-11e9-822c-47d3db34aba4.png)

I am thinking about to implement client validation using [vuelidate](https://github.com/monterail/vuelidate) or [VeeValidate](https://logaretm.github.io/vee-validate/)

Is there any way to somehow translate model attributes using `swagger-axios-codegen` and use them in validation?
Any ideas?

**Comment by denis-pujdak-adm-it** [comment]
Maybe it could be something like this?
```
ISwaggerOptions = {
  ...
  renderValidationModel: true | false,
  ...
}
```
```
export class RoleVm {
  /**  */
  name?: string;
  /**  */
  description?: string;
  /**  */
  static ValidationModel() {
    {
    name: {
      required,
      minLength: minLength(1),
      maxLength: maxLength(50)
    },
    age: {
      between: between(20, 30)
    }
  }
}
```
It is interesting how easy we can bind the validation model with the [vuelidate](https://github.com/monterail/vuelidate) or [VeeValidate](https://logaretm.github.io/vee-validate/)

**Comment by Manweill** [comment]
This is good idea. Welcome PR

**Comment by Manweill** [comment]
@denis-pujdak-adm-it  

Would you like to add an example to Readme？

**Comment by denis-pujdak-adm-it** [comment]
Hi @Manweill I am trying to integrate my project with [vuelidate](https://github.com/vuelidate/vuelidate). Ones I done with it I'm gonna add some small example to the readme file.

**Comment by fairking** [comment]
I did some work in my project. I decided that the only rules I need in javascript are actually `required` and `maxlength'. I am not going to use vuelidate or any other similar approach. Everything else is covered by server side validation. My axios receives the 400 errors with the following model `[{ field: 'name', message: 'The value must contain only letters and numbers' }]`. The model in my api is:
```c#
[Required]
[StringLength(50)]
[RegularExpression(@"^([a-zA-Z0-9])+$", ErrorMessage = "The value must contain only letters and numbers")]
public string Name { get; set; }
```
Where the `[Required]` and `[StringLength]` are covered by `swagger-axios-codegen`. All other validations are server side validations and I am happy with that approach. If anyone would like to include more validation rules into the `swagger-axios-codegen` feel free to create a PR.

My vuejs approach with `swagger-axios-codegen` validationModel:
Mixin:
```js
Vue.mixin(clientValidations());

function clientValidations() {
	return {
                data() {
			return {
				vModel: {},
			};
		},
		methods: {
			function isRequired(fieldName: string): boolean {
                            return (vModel && vModel[fieldName] && vModel[fieldName].required === true);
                        },
                        function maxLength(fieldName: string): number {
                            return (vModel && vModel[fieldName] && vModel[fieldName].maxLength ? vModel[fieldName].maxLength : 4000);
                        }
		},
	};
}
```
Component.vue
```html
<template>
        <label for="name">Name</name>
	<input id="name" type='text' v-model="model.name" :required="isRequired('name')" :maxlength="maxLength('name')" />
</template>

<script lang="ts">
	import Vue from "vue";

	export default Vue.extend({
                data() {
                    return {
                        model: new FooFormVm(),
                    }
                },
                created() {
                    this.vModel = FooFormVm.validationModel;
                },
	});
</script>
```
But I cannot see any problem with using vuelidate or vee-validate. You can easy translate the `validationModel` into rules your approach required. Please let me know what do you think guys.

**Comment by Manweill** [comment]
@fairking 
this issue can close?

**Comment by fairking** [comment]
Yes you can close. The most important things are covered. If someone needs more validation he/she can raise a new issue.
