### ISSUE TITLE
Option to split generated code in multiple files

### ISSUE THREAD

**Issue by Senci** [Manweill/swagger-axios-codegen#55]
Hey guys, I just started using `swagger-axios-codegen`.

Are there any technical issues why you aren't splitting the generated code into multiple files spread over multiple folders? And may this be an option for future releases?

**Comment by Manweill** [comment]
@Senci 
Yeah~file diff, and then it will generated more and more files

**Comment by nibytes** [comment]
On the one hand, this is a good idea, during updates only those files that need to be changed will change, on the other hand, this makes it difficult to track these very files.

**Comment by denis-pujdak-adm-it** [comment]
It could be an option to generate services in separate files by service tag name. And it could be useful when you have a lot of api and you want to `import` only what you want.

**Comment by Manweill** [comment]
@Senci @fairking 
Hei,  Multi-file mode has been implemented, can you please testing?
