### ISSUE TITLE
how do you think about includeOption use multimatch  do filter?

### ISSUE THREAD

**Issue by xxbld** [Manweill/swagger-axios-codegen#56]
[multimatch](https://github.com/sindresorhus/multimatch)
```json
[
"User",
"user*",
"!user*",
{"user":["get*","!set*"]}
]
```

**Comment by Manweill** [comment]
Briefly describe your usage and filtering rules

**Comment by xxbld** [comment]
`multimatch`  support include and exclude filter,
[case](https://github.com/sindresorhus/multimatch/blob/master/test/test.js)
easy to match tag-name ,path or operationId you want

**Comment by Manweill** [comment]
Got it.

**Comment by xxbld** [comment]
@Manweill  
我基本实现了这个功能,
因为匹配字符className里面有一些特殊字符 *,?,**,{},!, 所以要求严格按照 `pascalcase`规则书写；你看是沿用include参数还是怎么的？
![image](https://user-images.githubusercontent.com/13309211/75758569-3af35500-5d6f-11ea-8955-b422053ae90b.png)
![image](https://user-images.githubusercontent.com/13309211/75758508-2ca53900-5d6f-11ea-85d9-d6f141582838.png)

**Comment by Manweill** [comment]
@xxbb
用include参数吧，到时候把readme也修改一下

**Comment by xxbld** [comment]
https://github.com/Manweill/swagger-axios-codegen/pull/86/commits/61d414c8d99439ad9fa395f79252894706f3f535
