### ISSUE TITLE
Promise result is Any instead of the actual Type in open api v3

### ISSUE THREAD

**Issue by fairking** [Manweill/swagger-axios-codegen#69]
"swagger-axios-codegen": "0.9.10"
After switching my project to OpenApi v3 the rendered services lose the actual response type and have `any` instead. Is it intentional or a bug?
`/services/index.ts` changes after switching to v3:
![image](https://user-images.githubusercontent.com/13495631/72632505-4e2c9b80-394e-11ea-91d1-940835aa5b99.png)

The api v3 (Swashbuckle.AspNetCore 5.0.0):
![image](https://user-images.githubusercontent.com/13495631/72632602-83d18480-394e-11ea-8f05-5b5ba086fcf7.png)

Operation:
![image](https://user-images.githubusercontent.com/13495631/72633022-7e286e80-394f-11ea-8d57-74aab722129e.png)

Component:
![image](https://user-images.githubusercontent.com/13495631/72635017-bb8efb00-3953-11ea-9356-96400fda675e.png)

**Comment by denis-pujdak-adm-it** [comment]
I also don't see the `AddressFormVm` class rendered in `/services/index.ts`

**Comment by denis-pujdak-adm-it** [comment]
Also the generic class definition in C#:
```
PaginatedVm<AddressVm>
```
Changes its name from `PaginatedVm_AddressVm` to `AddressVmPaginatedVm`

But as I can see it is `Swashbuckle` change after upgrading from v4 to v5.

**Comment by denis-pujdak-adm-it** [comment]
PR is created https://github.com/Manweill/swagger-axios-codegen/pull/70

**Comment by fairking** [comment]
PR https://github.com/Manweill/swagger-axios-codegen/pull/71
