### ISSUE TITLE
useClassTransformer doesn't work when modelMode is set to interface

### ISSUE THREAD

**Issue by aranoe** [Manweill/swagger-axios-codegen#80]
**Problem Statement:**
As mentioned in #32 it is desirable to convert date types (`date` and `date-time`)  to `Date` object instead of `string`. This currently only works with `modelMode: "class"`. Setting `modelMode: "interface"` results in an error.

**How to reproduce:**
Run `swagger-axios-codegen` with following configuration:
```js
const { codegen } = require("swagger-axios-codegen");

codegen({
  methodNameMode: "operationId",
  remoteUrl: "https://petstore.swagger.io/v2/swagger.json", 
  useClassTransformer: true,
  outputDir: "./out",
  modelMode: "interface",
  useStaticMethod: true
});
```
**Example Error:**
> Argument of type 'unknown[]' is not assignable to parameter of type 'Pet | PromiseLike<Pet> | undefined'.
> Property 'then' is missing in type 'unknown[]' but required in type 'PromiseLike<Pet>'

In addition to that, dates are not transformed to `Date`:

```js
// https://petstore.swagger.io/v2/swagger.json
...
  "Order": {
    ...
     "shipDate": {
       "type": "string",
       "format": "date-time"
     }
    ...
  }
...
```
```ts
// generated index.ts
export interface Order {
 ...
  shipDate: string; // should be Date
 ...
}
```

**Comment by Manweill** [comment]
@aranoe 
`useClassTransformer`  is only work  in `modelMode='class'`

**Comment by aranoe** [comment]
I think this feature makes perfectly sense for interface models as well. If it's not possible to do with `useClassTransformer` another approach is desired. 
Maybe a configuration name like `useStringForDates` with default value `true` would be suitable.

**Comment by Manweill** [comment]
Can add a setting to format the response result with the `format` in the `swagger.json` specification.

**Comment by aranoe** [comment]
@Manweill The `format` is already set to `date-time` as shown in the opening post. The problem is, that `swagger-axios-codegen` still transforms this to a `string` type. But the desired type would/can be `Date` too. This is already possible with class models (`useClassTransformer`), but not with interfaces.

**Comment by aranoe** [comment]
I just looked at your code and saw that it should already produce `Date` by default, when `"type": "string"` and `"format": "date"` /`"format": "date-time"` 

https://github.com/aranoe/swagger-axios-codegen/blob/cb7bf85fe0f7db69b0131152b8f6cb64d9aff922/src/utils.ts#L86-L98

This seems like a bug now.

@Manweill can you confirm, when you run `swagger-axios-codegen` with the above configuration, that it also produces `string` instead of `Date` for `shipDate` in the `Order` model? I tested it multiple times now, with the same result.

**Comment by Manweill** [comment]
@aranoe 
Emm，I haven't actually used this feature, so you may need to discuss it with arkraft or you can submit your new idea. 
Welcome PR.
