### ISSUE TITLE
Error: please inject yourself instance like axios

### ISSUE THREAD

**Issue by skazakovstas** [Manweill/swagger-axios-codegen#81]
Good afternoon.
Thanks so much for a great plugin.

Help to deal with the question.
I use the generated code in VUE. When I try to access the method, I get an error in the promise ("Error: please inject yourself instance like axios"). 

Thanks for the help

**Comment by Manweill** [comment]
@skazakovstas 
Do you mind the settings I look at?

**Comment by skazakovstas** [comment]
In VUE component

`<script>
    import Vue from 'vue'
    import axios from 'axios'
    import {ProjectService} from '../../index.js'

    Vue.use(axios)

    const instance = axios.create({
        baseURL: '/api',
        timeout: 1000,
        headers: {'X-Custom-Header': 'foobar'}
    });

    ProjectService.axios = instance

    export default {
        data: () => ({
            all_project: [],
        }),

        mounted() {
            /**
             * Get all project on mount component
             */
            ProjectService.projectGet().then(response => {
                console.log(response.data)
                this.all_project = response.data
            })       
        }
    }
</script>`

This is `'import {ProjectService} from '../../index.js'` generated from spec.json file, wich is transpile in to js.

**Comment by Manweill** [comment]
`ProjectService.axios` ? 不应该是 `serviceOptions.axios` 吗

**Comment by skazakovstas** [comment]
Yes, it worked. Thanks again.
