### ISSUE TITLE
Trouble with generating an array of number enums

### ISSUE THREAD

**Issue by morbalint** [Manweill/swagger-axios-codegen#9]
The generator removes an array from the swagger.json schema when the array contains a number enum.
simplified example:
```json
{ 
  "definitions": {
    "MyModel": {
      "type":"object",
      "properties": {
          "foo": {
          "uniqueItems": true,
          "type": "array",
          "items": {
            "format": "int32",
            "enum": [
              0,
              1,
              2,
              4,
              8
            ],
            "type": "integer"
          }
        },
      }
    }
  }
}
```

the generated class will look something like this:
```typescript
export class MyModel {
  foo: 0 | 1 | 2 | 4 | 8;
  constructor(data?: any) {
    if (data) {
      this['foo'] = data['foo'];
    }
  }
}
```

Sorry for the low quality example :(

I believe, I have found the error, and I will create a PR later.

Can you confirm its still an issue in your latest development branch ?

**Comment by Manweill** [comment]
Sure, I will confirm it

**Comment by Manweill** [comment]
I fix it ,it will generate like this:
```js

type INumberArrayEnumModelFoo = 0 | 1 | 2 | 4 | 8;

export class NumberArrayEnumModel {
  /**  */
  foo: INumberArrayEnumModelFoo[]

  constructor(data?: any) {
    if (data) {
      this['foo'] = data['foo'];
    }
  }
}
```

**Comment by morbalint** [comment]
Thank you!

**Comment by Manweill** [comment]
You are welcome! 
Thank you for your interest in this library and application to the actual project.

**Comment by morbalint** [comment]
Hi!

I tried, your fix and found an error with it. When you have more than one number enum, the generator does not separate the types and creates file with wrong syntax.

Created pull request with example to show, and a fix.

Should, this be a separate issue, or can we track it in this one?

Also, what is your release process, should I increase the version number and add the issue to the changelog ?

**Comment by Manweill** [comment]
I reopen this issue.
When i publish, I will test the example with the generator.
The test is passed, add the issue to the changelog and increase the version

**Comment by Manweill** [comment]
@morbalint 
The PR #11 need me publish now?
