### ISSUE TITLE
Query parameters with empty description are skipped

### ISSUE THREAD

**Issue by OndraRehounek** [Manweill/swagger-axios-codegen#91]
Hi,

I just discovered that query parameters that have empty description are not converted into TypeScript. If I manually fill the description atribute, everything works as expected.

JSON is generated from Django REST framework Swagger generator - https://drf-yasg.readthedocs.io/en/stable/readme.html

I am not sure if this is "bug" or "feature" so please handle this issue as you want and thank you for the awesome work you are doing.

 ```
   "parameters": [
      {
        "name": "study_id",
        "in": "query",
        "description": "",
        "required": false,
        "type": "string"
      },
      {
        "name": "page",
        "in": "query",
        "description": "A page number within the paginated result set.",
        "required": false,
        "type": "integer"
      },
      {
        "name": "page_size",
        "in": "query",
        "description": "Number of results to return per page.",
        "required": false,
        "type": "integer"
      }
    ],
```

Whole endpoint here, in case it helps: 
```
"/sites/": {
  "get": {
    "operationId": "sites_list",
    "description": "",
    "parameters": [
      {
        "name": "study_id",
        "in": "query",
        "description": "",
        "required": false,
        "type": "string"
      },
      {
        "name": "page",
        "in": "query",
        "description": "A page number within the paginated result set.",
        "required": false,
        "type": "integer"
      },
      {
        "name": "page_size",
        "in": "query",
        "description": "Number of results to return per page.",
        "required": false,
        "type": "integer"
      }
    ],
    "responses": {
      "200": {
        "description": "",
        "schema": {
          "required": [
            "count",
            "results"
          ],
          "type": "object",
          "properties": {
            "count": {
              "type": "integer"
            },
            "next": {
              "type": "string",
              "format": "uri",
              "x-nullable": true
            },
            "previous": {
              "type": "string",
              "format": "uri",
              "x-nullable": true
            },
            "results": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Site"
              }
            }
          }
        }
      }
    },
    "tags": [
      "sites"
    ]
  },
  "post": {
    "operationId": "sites_create",
    "description": "",
    "parameters": [
      {
        "name": "data",
        "in": "body",
        "required": true,
        "schema": {
          "$ref": "#/definitions/Site"
        }
      }
    ],
    "responses": {
      "201": {
        "description": "",
        "schema": {
          "$ref": "#/definitions/Site"
        }
      }
    },
    "tags": [
      "sites"
    ]
  },
  "parameters": [
    
  ]
},
```

**Comment by Manweill** [comment]
@OndraRehounek 
You need to check your request `/sites/` url. It is wrong?

**Comment by OndraRehounek** [comment]
@Manweill  you mean to check if the request is sent properly? 

The error is risen even before since I cannot pass the "study_id" parameter to the generated method without violating the Typescript definitions because the parametr is not listed in the params of the method.

If we fill the description of the "study_id" parameter, the GET method for the /sites/ URL is generated properly and it accepts study_id (studyId) as expected.

**Comment by Manweill** [comment]
@OndraRehounek 
You can try it. 
I copy your spec in example project and build it, it does not generated. Of course you can also provide examples repo.

**Comment by Manweill** [comment]
I mean, your spec is wrong in` /sites/`, it should be written as `/sites`

**Comment by OndraRehounek** [comment]
Hi @Manweill , thank you for the response. I spent an hour trying to replicate the issue but now without success - it works same with `/sites/` or `/sites` and it works with empty description as well...

I used same JSON that was not working before so I am really puzzled...

Thanks again for your time, I'll close the issue.
