### ISSUE TITLE
Problems with multipart/form-data request generations

### ISSUE THREAD

**Issue by klimentru1986** [Manweill/swagger-axios-codegen#93]
I need to generate api with a `multipart/form-data`, but is's not work.

I found a problem.

The type in the old version [swagger 2.0](https://swagger.io/docs/specification/2-0/file-upload/) was in a `consumes` section.

The type in the [current version](https://swagger.io/docs/specification/describing-request-body/file-upload/) is placed in a `content` section.

You check only `consumes` section in you library. And the api with the `multipart/form-data` type isn't generated.

https://github.com/Manweill/swagger-axios-codegen/blob/v0.3/src/requestCodegen/index.ts#L25

Please fix it.

**Comment by Manweill** [comment]
@klimentru1986 
Welcome to PR.

**Comment by klimentru1986** [comment]
> @klimentru1986
> Welcome to PR.

Done. #94
